version: '3'
services:
  fiscal_container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VAULT_URL=${VAULT_URL}
        - VAULT_NAMESPACE=${VAULT_NAMESPACE}
        - VAULT_TOKEN=${VAULT_TOKEN}
    container_name: fiscal_container
    image: "${DOCKERHUB_USERNAME}/fiscal-dash:${DATE}"
    environment:
      - IMAGE_NAME="${DOCKERHUB_USERNAME}/fiscal-dash:${DATE}"
    networks:
      default:
        ipv4_address: 172.28.0.2

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16