apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fiscal-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiscal-dash
  template:
    metadata:
      labels:
        app: fiscal-dash
    spec:
      containers:
      - name: fiscal-dash
        image: danlh/fiscal-dash:20230701104721
        ports:
        - containerPort: 5000
          name: webapp
        envFrom:
        - secretRef:
            name: fiscal-secrets
