apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fiscal-dash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiscal-dash
  template:
    metadata:
      labels:
        app: fiscal-dash
        pod-index: "$(POD_INDEX)"
    spec:
      containers:
      - name: fiscal-dash
        image: danlh/fiscal-dash:20230701104721
        ports:
        - containerPort: 5000
          name: webapp
        env:
        - name: POD_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-index']
        envFrom:
        - secretRef:
            name: fiscal-secrets
