apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: fiscal-dash
spec:
  selector:
    app: fiscal-dash
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: webapp