apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fiscal-dash
  labels:
    app: fiscal-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiscal-dash
  template:
    metadata:
      labels:
        app: fiscal-dash
    spec:
      containers:
      - name: fiscal-dash
        image: danlh/fiscal-dash:latest
        ports:
        - containerPort: 5000