apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiscal-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiscal-dash
  serviceName: fiscal-dash
  template:
    metadata:
      labels:
        app: fiscal-dash
    spec:
      containers:
        - name: fiscal-dash
          image: danlh/fiscal-dash:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
