# This workflow will pull dependencies from cache, check for new requirements/requirements and push back into cache. Then run a safety check

name: Dependencies

on:
  push:
    branches: [ "master" ]

jobs:
  sync_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python and access pip cache
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements/test.txt'
    
    - name: Install dependencies
      run: pip install -r requirements/test.txt
    
    - name: Run safety on current dependencies
      run: safety check --file requirements/test.txt --full-report
      
    - name: Lint with Flake8
      if: success()
      run: flake8 || exit 0
      continue-on-error: true

    - name: Lint with Pylint
      run: pylint **/*.py || exit 0
      continue-on-error: true

    - name: Lint with Ruff
      run: ruff **/*.py || exit 0
      continue-on-error: true
  
    - name: Run pytest
      run: pytest

    - name: Run unittest
      run: python -m unittest