name: 2. Packed Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          VAULT_URL: ${{ secrets.VAULT_URL }}
          VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          docker buildx build --platform linux/amd64 -t $DOCKERHUB_USERNAME/fiscal-dash:latest --push --build-arg VAULT_URL=$VAULT_URL --build-arg VAULT_NAMESPACE=$VAULT_NAMESPACE --build-arg VAULT_TOKEN=$VAULT_TOKEN .

      - name: Pull Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker pull $DOCKERHUB_USERNAME/fiscal-dash:latest

      - name: Run Docker container
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker run -d --name fiscal_container $DOCKERHUB_USERNAME/fiscal-dash:latest

      - name: Run Tests
        run: docker exec -w /app fiscal_container pytest

      - name: Stop and remove container
        run: docker stop fiscal_container && docker rm fiscal_container