name: 2. Packed Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        id: build
        env:
          VAULT_URL: ${{ secrets.VAULT_URL }}
          VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: docker compose up -d

      - name: Wait for Pytest to run
        run: sleep 30

      - name: Create 'mylogs' directory
        run: mkdir mylogs

      - name: Retrieve App and Container Logs
        run: |
          docker logs fiscal_container > mylogs/container_logs.txt 2>&1

      - name: Push working image to Docker Hub
        run: docker push $IMAGE_NAME

      - name: Stop and remove container
        run: docker stop fiscal_container && docker rm fiscal_container
      
      - name: Archive Logs Directory as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: mylogs
