name: 2. Packed Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          VAULT_URL: ${{ secrets.VAULT_URL }}
          VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          VERSION=$(date +"%Y%m%d%H%M%S")
          IMAGE_TAG=$DOCKERHUB_USERNAME/fiscal-dash:$VERSION
          docker buildx build --platform linux/amd64 -t $IMAGE_TAG --build-arg VAULT_URL=$VAULT_URL --build-arg VAULT_NAMESPACE=$VAULT_NAMESPACE --build-arg VAULT_TOKEN=$VAULT_TOKEN .

      - name: Run Docker container
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo $IMAGE_TAG
          docker run -d --name fiscal_container $IMAGE_TAG

      - name: Wait for Pytest to run
        run: sleep 30

      - name: Create 'mylogs' directory
        run: mkdir mylogs

      - name: Retrieve App and Container Logs
        run: |
          docker logs fiscal_container > mylogs/container_logs.txt 2>&1

      - name: Push working image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker push $IMAGE_TAG

      - name: Stop and remove container
        run: docker stop fiscal_container && docker rm fiscal_container
      
      - name: Archive Logs Directory as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: mylogs
