name: Unpacked Tests

on:
  workflow_run:
    workflows: ["Dependencies"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Python and access pip cache
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements/test.txt'

      - name: Lint with Flake8
        run: flake8 || exit 0
        continue-on-error: true

      - name: Lint with Pylint
        run: pylint **/*.py || exit 0
        continue-on-error: true

      - name: Lint with Ruff
        run: ruff **/*.py || exit 0
        continue-on-error: true
    
      - name: Run pytest
        run: pytest

      - name: Run unittest
        run: python -m unittest